openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-postgresql
components:
  schemas:
    variables:
      required: 
      - architecture
      - engine_version
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          nullable: true
          properties:
            service_type:
              description: |
                Specify the service type of the Kubernetes cluster, default is `NodePort`.
              default: "NodePort"
              nullable: true
              title: Service Type
              type: string
              enum:
              - NodePort
              - LoadBalancer
              - ClusterIP
              x-walrus-ui:
                order: 4
            domain_suffix:
              description: |
                Specify the domain name of the Kubernetes cluster.
              default: cluster.local
              nullable: true
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            image_registry:
              description: |
                Specify the image registry to pull the bitnami/postgresql image, default is `registry-1.docker.io`.
              default: registry-1.docker.io
              nullable: true
              title: Image Registry
              type: string
              x-walrus-ui:
                order: 2
            namespace:
              title: Namespace
              type: string
              nullable: true
              x-walrus-ui:
                hidden: true
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          nullable: true
          enum:
          - 1
          - 2
          - 3
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/postgresql/tags.
          default: "15.0"
          x-walrus-ui:
            group: Basic
            order: 5
        database:
          title: Database
          type: string
          description: |
            Specify the database name. The database name must be 2-64 characters long and start with any lower letter, combined with number, or symbols: - _. 
            The database name cannot be PostgreSQL forbidden keyword.
          default: mydb
          nullable: true
          maxLength: 64
          minLength: 2
          x-walrus-ui:
            group: Basic
            order: 8
        username:
          title: Username
          type: string
          description: |
            Specify the account username. The username must be 2-16 characters long and start with lower letter(expect `pg` prefix), combined with number, or symbol: _.
            The username cannot be PostgreSQL forbidden keyword and postgres.
          default: rdsuser
          nullable: true
          maxLength: 16
          minLength: 2
          x-walrus-ui:
            group: Basic
            order: 6
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 8-32 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          nullable: true
          maxLength: 32
          minLength: 8
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 7
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            cpu: 0.25
            memory: 1024
          nullable: true
          properties:
            cpu:
              description: |
                Specify the cpu resources. Unit is core.
              default: 0.25
              minimum: 0.1
              nullable: true
              title: Cpu(Core)
              type: number
              x-walrus-ui:
                order: 1
            memory:
              description: |
                Specify the memory resources. Unit is megabyte.
              default: 1024
              minimum: 512
              nullable: true
              title: Memory(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          nullable: true
          properties:
            class:
              description: |
                Specify the storage class. If not specified, it will use the default provisioner.
              nullable: true
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              description: |
                Specify the storage size. Unit is megabyte.
              default: 10240
              minimum: 1024
              nullable: true
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 10
        seeding:
          title: Seeding
          type: object
          description: |
            Specify the configuration to seed the database at first-time creating.
            Seeding increases the startup time waiting and also needs
            proper permission, like root account.
          nullable: true
          required:
          - type
          properties:
            text:
              description: |
                Configure database seeding from text.
              nullable: true
              properties:
                content:
                  description: |
                    Specify the SQL statements to seed the database.
                  title: Content
                  type: string
              required:
              - content
              title: Text
              type: object
              x-walrus-ui:
                colSpan: 12
                group: Basic
                showIf: type=text
                order: 2
            type:
              description: |
                Specify the seeding approach, select from none, url or text.
              default: none
              enum:
              - none
              - url
              - text
              title: Type
              type: string
              x-walrus-ui:
                order: 1
            url:
              description: |
                Configure database seeding from URL.
              nullable: true
              properties:
                location:
                  description: |
                    Specify the URL to download the SQL statements.
                  title: Location
                  type: string
                  x-walrus-ui:
                    order: 1
                storage:
                  description: |
                    Specify a storage to store the downloaded SQL statements.
                  nullable: true
                  properties:
                    class:
                      description: |
                        Specify the storage class. If not specified, it will use the default provisioner.
                      nullable: true
                      title: Class
                      type: string
                      x-walrus-ui:
                        order: 1
                    size:
                      description: |
                        Specify the storage size. Unit is megabyte.
                      default: 10240
                      minimum: 1024
                      nullable: true
                      title: Size(MiB)
                      type: number
                      x-walrus-ui:
                        order: 2
                  title: Storage
                  type: object
                  x-walrus-ui:
                    colSpan: 12
                    order: 2
              required:
              - location
              title: Url
              type: object
              x-walrus-ui:
                colSpan: 12
                showIf: type=url
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 11
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
